# Generated by Django 5.0.6 on 2024-07-09 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.TextField(blank=True, null=True)),
                ('position', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='Entities',
            fields=[
                ('ent_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'entities',
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('taskid', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('creator', models.IntegerField(blank=True, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('media_type', models.TextField(blank=True, null=True)),
                ('media_id', models.IntegerField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('priority', models.TextField(blank=True, null=True)),
                ('result', models.TextField(blank=True, null=True)),
                ('resulttype', models.TextField(blank=True, null=True)),
                ('resultid', models.IntegerField(blank=True, null=True)),
                ('act', models.IntegerField(blank=True, null=True)),
                ('actid', models.TextField(blank=True, null=True)),
                ('acttype', models.TextField(blank=True, null=True)),
                ('agreement', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('entity', models.ForeignKey(blank=True, db_column='entity', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='supp.entities')),
                ('slave', models.ForeignKey(blank=True, db_column='slave', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='supp.employees')),
            ],
            options={
                'db_table': 'tasks',
            },
        ),
    ]
