# Generated by Django 5.0.6 on 2024-07-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entities',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
