# Generated by Django 5.0.6 on 2024-07-10 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supp', '0002_entities_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employees',
            options={'verbose_name': 'Работник', 'verbose_name_plural': 'Работники'},
        ),
        migrations.AlterModelOptions(
            name='entities',
            options={'verbose_name': 'Объект', 'verbose_name_plural': 'Объекты'},
        ),
    ]
