# Generated by Django 5.0.6 on 2024-07-18 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supp', '0003_alter_employees_options_alter_entities_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterField(
            model_name='tasks',
            name='agreement',
            field=models.TextField(blank=True, null=True, verbose_name='Соглашение'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='creator',
            field=models.IntegerField(blank=True, null=True, verbose_name='Создал'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='priority',
            field=models.TextField(blank=True, null=True, verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.TextField(blank=True, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий к закрытию'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='Тема'),
        ),
    ]
