# Generated by Django 5.0.6 on 2024-07-18 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supp', '0004_alter_tasks_options_alter_tasks_agreement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='entity',
            field=models.ForeignKey(blank=True, db_column='entity', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='supp.entities', verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='slave',
            field=models.ForeignKey(blank=True, db_column='slave', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='supp.employees', verbose_name='Исполнитель'),
        ),
    ]
