# Generated by Django 5.0.6 on 2024-08-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supp', '0005_alter_tasks_entity_alter_tasks_slave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='media_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='resultid',
            field=models.TextField(blank=True, null=True),
        ),
    ]
