# Generated by Django 5.0.6 on 2024-11-27 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supp', '0008_alter_carsinuse_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('object', models.ForeignKey(blank=True, db_column='object', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='supp.entities')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'db_table': 'customers',
                'managed': True,
            },
        ),
    ]
